#!/bin/bash
set -euo pipefail

# sf-apply-spec.sh — trusted state-transition step for stage 1 (specs).
#
# The /sf-tospecs skill only *generates* a spec (untrusted output). This script
# validates that output and advances the label state machine:
#   feedback/bug|feedback/feature  --(add)-->  sf:spec
# The bug/feature classification label is KEPT (permanent metadata); sf:spec is
# an additive stage marker. Stage progression = highest sf: label present.
#
# Usage: sf-apply-spec.sh <issue-number> <spec-log-file>
#   The log file is the captured stdout of `claude -p /sf-tospecs <n>`, which
#   contains the spec markdown inside a <!--SPEC--> ... <!--/SPEC--> block.

REPO="${SF_REPO:-$(gh repo view --json nameWithOwner -q .nameWithOwner 2>/dev/null || echo kilo9alfa/softwarefactory)}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG_DIR="${HOME}/.local/share/softwarefactory/logs"
mkdir -p "$LOG_DIR"

log() {
    echo "[$(date '+%Y.%m.%d %H:%M:%S')] [apply-spec] $*" | tee -a "$LOG_DIR/dispatcher.log"
}

issue_num="${1:?usage: sf-apply-spec.sh <issue-number> <spec-log-file>}"
spec_log="${2:?usage: sf-apply-spec.sh <issue-number> <spec-log-file>}"

if [ ! -f "$spec_log" ]; then
    log "Issue #$issue_num: spec log '$spec_log' not found, aborting"
    exit 1
fi

# Idempotency + stage guards.
current_labels=$(gh issue view "$issue_num" --repo "$REPO" --json labels --jq '.labels[].name' 2>/dev/null || echo "")
if echo "$current_labels" | grep -qx "sf:spec"; then
    log "Issue #$issue_num: sf:spec already present, already processed — skipping"
    exit 0
fi
if ! echo "$current_labels" | grep -qE "^feedback/(bug|feature)$"; then
    log "Issue #$issue_num: no feedback/bug|feature label — not ready for spec, skipping"
    exit 1
fi

# Extract the spec between the markers. Never eval or execute the content.
spec=$(sed -n '/<!--SPEC-->/,/<!--\/SPEC-->/p' "$spec_log" | sed '/<!--SPEC-->/d; /<!--\/SPEC-->/d')

if [ -z "${spec// /}" ]; then
    log "Issue #$issue_num: no <!--SPEC--> block found in output, leaving stage unchanged"
    exit 1
fi

log "Issue #$issue_num: spec extracted (${#spec} chars) -> posting + adding sf:spec"

# Post the spec as a comment. AI disclaimer + spec content quoted as data.
comment_body="🏭 **Spec** (generated by \`/sf-tospecs\`)"$'\n\n'"> This was generated by AI during the spec stage."$'\n\n'"${spec}"
gh issue comment "$issue_num" --repo "$REPO" --body "$comment_body"

# Advance the state machine: add sf:spec, keep the classification label.
gh issue edit "$issue_num" --repo "$REPO" --add-label "sf:spec"

bash "$SCRIPT_DIR/sf-notify.sh" "✅ Spec ready for #${issue_num} — tickets next" >/dev/null 2>&1 || true
log "Issue #$issue_num state transition complete (sf:spec)"
