#!/bin/bash
set -euo pipefail

# sf-apply-tickets.sh — trusted state-transition step for stage 2 (tickets).
#
# The /sf-totickets skill only *emits* a format-agnostic JSON ticket array
# (untrusted output). This script validates it, RENDERS a dependency-ordered
# checklist comment, and advances the label state machine:
#   sf:1-spec  --(add)-->  sf:2-tickets
#
# The JSON format is deliberately renderer-agnostic: today we render a checklist;
# a future version can create child GitHub issues from the SAME JSON without any
# change to the skill.
#
# Usage: sf-apply-tickets.sh <issue-number> <tickets-log-file>
#   The log file is the captured stdout of `claude -p /sf-totickets <n>`,
#   containing the ticket JSON (optionally inside a ```json fence).

REPO="${SF_REPO:-$(gh repo view --json nameWithOwner -q .nameWithOwner 2>/dev/null || true)}"
: "${REPO:?SF_REPO unset and gh cannot resolve the repo -- run inside the repo, set SF_REPO, or export GH_TOKEN}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG_DIR="${HOME}/.local/share/softwarefactory/logs"
mkdir -p "$LOG_DIR"

log() {
    echo "[$(date '+%Y.%m.%d %H:%M:%S')] [apply-tickets] $*" | tee -a "$LOG_DIR/dispatcher.log"
}

issue_num="${1:?usage: sf-apply-tickets.sh <issue-number> <tickets-log-file>}"
tickets_log="${2:?usage: sf-apply-tickets.sh <issue-number> <tickets-log-file>}"

if [ ! -f "$tickets_log" ]; then
    log "Issue #$issue_num: tickets log '$tickets_log' not found, aborting"
    exit 1
fi

# Idempotency + stage guards.
current_labels=$(gh issue view "$issue_num" --repo "$REPO" --json labels --jq '.labels[].name' 2>/dev/null || echo "")
if echo "$current_labels" | grep -qx "sf:2-tickets"; then
    log "Issue #$issue_num: sf:2-tickets already present, already processed — skipping"
    exit 0
fi
if ! echo "$current_labels" | grep -qx "sf:1-spec"; then
    log "Issue #$issue_num: no sf:1-spec label — not ready for tickets, skipping"
    exit 1
fi

# Extract the JSON object. Prefer a ```json fenced block; fall back to the first
# {...} object. Never eval or execute the content.
json=$(sed -n '/```json/,/```/p' "$tickets_log" | sed '/```/d')
if [ -z "$json" ]; then
    json=$(sed -n '/{/,/}/p' "$tickets_log")
fi

if [ -z "$json" ]; then
    log "Issue #$issue_num: no JSON found in tickets output, leaving stage unchanged"
    exit 1
fi

# Validate: .tickets must be a non-empty array. -e makes jq fail on false/null.
if ! echo "$json" | jq -e '.tickets | type == "array" and length > 0' >/dev/null 2>&1; then
    log "Issue #$issue_num: tickets JSON invalid or empty, leaving stage unchanged"
    exit 1
fi

# Render a dependency-ordered checklist. blocked_by ids become "(after N, M)".
checklist=$(echo "$json" | jq -r '
    .tickets[]
    | "- [ ] **\(.title)**"
      + (if (.blocked_by // [] | length) > 0
         then " (after \(.blocked_by | map(tostring) | join(", ")))"
         else "" end)
      + (if (.body // "") != "" then "  \n  \(.body)" else "" end)
')

if [ -z "$checklist" ]; then
    log "Issue #$issue_num: checklist rendered empty, aborting"
    exit 1
fi

ticket_count=$(echo "$json" | jq -r '.tickets | length')
log "Issue #$issue_num: $ticket_count ticket(s) rendered -> posting + adding sf:2-tickets"

# Post the checklist. AI disclaimer; ticket text quoted as data, never executed.
comment_body="🏭 **Tickets** (${ticket_count} vertical slices, via \`/sf-totickets\`)"$'\n\n'"> This was generated by AI during the ticket stage."$'\n\n'"${checklist}"
gh issue comment "$issue_num" --repo "$REPO" --body "$comment_body"

# Advance the state machine: add sf:2-tickets, keep prior labels.
gh issue edit "$issue_num" --repo "$REPO" --add-label "sf:2-tickets"

bash "$SCRIPT_DIR/sf-notify.sh" "🎯 Tickets ready for #${issue_num} (${ticket_count} slices) — planning next" >/dev/null 2>&1 || true
log "Issue #$issue_num state transition complete (sf:2-tickets)"
