#!/bin/bash
set -euo pipefail

# sf-apply-plan.sh — trusted state-transition step for stage 3a (planning).
#
# The /sf-plan skill only *generates* a plan (untrusted output). This script
# validates it, posts it, and parks the issue at the HUMAN APPROVAL GATE:
#   sf:2-tickets  --(add)-->  sf:3-plan-review
# It deliberately does NOT set sf:3-plan-approved — that transition is human-only
# (see sf-approve-plan.sh). Plan generation is autonomous; plan approval is not.
#
# Usage: sf-apply-plan.sh <issue-number> <plan-log-file>
#   The log file is the captured stdout of `claude -p /sf-plan <n>`, which
#   contains the plan markdown inside a <!--PLAN--> ... <!--/PLAN--> block.

REPO="${SF_REPO:-$(gh repo view --json nameWithOwner -q .nameWithOwner 2>/dev/null || true)}"
: "${REPO:?SF_REPO unset and gh cannot resolve the repo -- run inside the repo, set SF_REPO, or export GH_TOKEN}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG_DIR="${HOME}/.local/share/softwarefactory/logs"
mkdir -p "$LOG_DIR"

log() {
    echo "[$(date '+%Y.%m.%d %H:%M:%S')] [apply-plan] $*" | tee -a "$LOG_DIR/dispatcher.log"
}

issue_num="${1:?usage: sf-apply-plan.sh <issue-number> <plan-log-file>}"
plan_log="${2:?usage: sf-apply-plan.sh <issue-number> <plan-log-file>}"

if [ ! -f "$plan_log" ]; then
    log "Issue #$issue_num: plan log '$plan_log' not found, aborting"
    exit 1
fi

# Idempotency + stage guards.
current_labels=$(gh issue view "$issue_num" --repo "$REPO" --json labels --jq '.labels[].name' 2>/dev/null || echo "")
if echo "$current_labels" | grep -qE "^sf:3-plan-review$|^sf:3-plan-approved$"; then
    log "Issue #$issue_num: already at/past plan-review, skipping"
    exit 0
fi
if ! echo "$current_labels" | grep -qx "sf:2-tickets"; then
    log "Issue #$issue_num: no sf:2-tickets label — not ready for plan, skipping"
    exit 1
fi

# Extract the plan between the markers. Never eval or execute the content.
plan=$(sed -n '/<!--PLAN-->/,/<!--\/PLAN-->/p' "$plan_log" | sed '/<!--PLAN-->/d; /<!--\/PLAN-->/d')

if [ -z "${plan// /}" ]; then
    log "Issue #$issue_num: no <!--PLAN--> block found in output, leaving stage unchanged"
    exit 1
fi

log "Issue #$issue_num: plan extracted (${#plan} chars) -> posting + adding sf:3-plan-review"

# Post the plan as a comment. AI disclaimer + plan content quoted as data.
comment_body="🏭 **Implementation Plan** (generated by \`/sf-plan\`)"$'\n\n'"> This was generated by AI during the planning stage. **Awaiting human approval** — add the \`sf:3-plan-approved\` label (or run \`sf-approve-plan.sh ${issue_num}\`) to unblock development."$'\n\n'"${plan}"
gh issue comment "$issue_num" --repo "$REPO" --body "$comment_body"

# Advance to the approval gate: add sf:3-plan-review, keep prior labels.
gh issue edit "$issue_num" --repo "$REPO" --add-label "sf:3-plan-review"

bash "$SCRIPT_DIR/sf-notify.sh" "📋 Plan ready for approval on #${issue_num} (@david) — review, then add \`sf:3-plan-approved\` (or run sf-approve-plan.sh ${issue_num})" >/dev/null 2>&1 || true
log "Issue #$issue_num parked at approval gate (sf:3-plan-review)"
