#!/bin/bash
set -uo pipefail

# sf-revise.sh — roll an issue back to an earlier pipeline stage so the human's
# edits to the issue get regenerated forward. The dispatcher is a pure LABEL
# state-machine: editing the issue body does nothing until a stage's done-label
# is removed. This collapses "remove the right labels + clear retry markers" into
# one command.
#
# Usage:
#   sf-revise.sh <issue> <stage> [--dry-run]
#
#   <stage>   spec | tickets | plan   — the EARLIEST stage to regenerate.
#             Rolling back to a stage also rolls back every stage after it
#             (they were derived from the version you're replacing).
#   --dry-run print what it would do, change nothing.
#
# The superseded spec/tickets/plan bot comments are ALWAYS deleted, so the re-run
# reads a clean issue instead of stacking a v2 under the v1.
#
# Workflow:
#   1. Edit the issue body (sharpen problem / solution / scope).
#   2. sf-revise.sh <issue> spec          # (or tickets / plan)
#   3. Next dispatcher tick (<=5 min) regenerates forward and re-parks at
#      sf:plan-review. Iterate as many rounds as you like.
#
# Repo/identity: SF_REPO -> gh (cwd) -> fail cleanly, same as the other scripts.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG_DIR="${HOME}/.local/share/softwarefactory/logs"

DRYRUN=0; ISSUE=""; STAGE=""
while [ $# -gt 0 ]; do
    case "$1" in
        --dry-run) DRYRUN=1 ;;
        -h|--help) sed -n '3,26p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
        spec|tickets|plan) STAGE="$1" ;;
        *) if [ -z "$ISSUE" ] && printf '%s' "$1" | grep -qE '^[0-9]+$'; then ISSUE="$1"
           else echo "unknown/invalid argument: $1 (see --help)" >&2; exit 1; fi ;;
    esac
    shift
done

[ -z "$ISSUE" ] && { echo "error: issue number required (see --help)" >&2; exit 1; }
[ -z "$STAGE" ] && { echo "error: stage required: spec | tickets | plan (see --help)" >&2; exit 1; }

REPO="${SF_REPO:-$(gh repo view --json nameWithOwner -q .nameWithOwner 2>/dev/null || true)}"
: "${REPO:?SF_REPO unset and gh cannot resolve the repo -- run inside the repo, set SF_REPO, or export GH_TOKEN}"

run() { if [ "$DRYRUN" -eq 1 ]; then echo "  [dry-run] $*"; else eval "$@"; fi; }

# --- what to roll back ---------------------------------------------------------
# Generative stages, in order, and the done-label(s) each one sets.
# Rolling back to STAGE removes STAGE's label + everything downstream of it.
case "$STAGE" in
    spec)    remove_labels="sf:spec sf:tickets sf:plan-review sf:plan-approved"
             clear_markers="spec tickets plan dev test" ;;
    tickets) remove_labels="sf:tickets sf:plan-review sf:plan-approved"
             clear_markers="tickets plan dev test" ;;
    plan)    remove_labels="sf:plan-review sf:plan-approved"
             clear_markers="plan dev test" ;;
esac
# Post-plan machine stages are always downstream — clear them regardless.
remove_labels="$remove_labels sf:implemented sf:ready-for-prod sf:needs-debug sf:deploy-failed"
# Comment signatures to prune, per stage (matched at start of body).
declare -A SIG=(
    [spec]="🏭 **Spec** (generated by"
    [tickets]="🏭 **Tickets** ("
    [plan]="🏭 **Implementation Plan** (generated by"
)
case "$STAGE" in
    spec)    prune_stages="spec tickets plan" ;;
    tickets) prune_stages="tickets plan" ;;
    plan)    prune_stages="plan" ;;
esac

echo "🏭 sf-revise #$ISSUE → regenerate from '$STAGE' on $REPO"

# --- current labels (only remove what's actually present) ----------------------
current=$(gh issue view "$ISSUE" --repo "$REPO" --json labels --jq '.labels[].name' 2>/dev/null || echo "")
if [ -z "$current" ]; then echo "error: issue #$ISSUE not found on $REPO" >&2; exit 1; fi

# Safety: warn if dev already ran — a worktree + draft PR exist that this won't undo.
if printf '%s\n' "$current" | grep -qx "sf:implemented"; then
    echo "  ⚠️  #$ISSUE is already 'sf:implemented' — a worktree + draft PR exist."
    echo "      This rolls the LABELS back, but does NOT delete the branch/PR/worktree."
    echo "      Close the draft PR + 'git worktree remove' manually if you want a clean redo."
fi

to_remove=""
for l in $remove_labels; do
    printf '%s\n' "$current" | grep -qx "$l" && to_remove="$to_remove $l"
done
if [ -n "$to_remove" ]; then
    args=""; for l in $to_remove; do args="$args --remove-label \"$l\""; done
    run "gh issue edit \"$ISSUE\" --repo \"$REPO\"$args"
    echo "  ✓ removed labels:$to_remove"
else
    echo "  (no matching done-labels present — nothing to remove; already at/behind '$STAGE')"
fi

# --- clear retry markers (so the re-run isn't blocked by the retry cap) --------
for s in $clear_markers; do
    run "rm -f \"$LOG_DIR/$s-$ISSUE.attempts\" \"$LOG_DIR/$s-$ISSUE.log\" \"$LOG_DIR/$s-$ISSUE.gaveup\""
done
echo "  ✓ cleared retry markers: $clear_markers"

# --- delete superseded bot comments (always) -----------------------------------
pruned=0
while IFS=$'\t' read -r cid body; do
    [ -z "$cid" ] && continue
    for s in $prune_stages; do
        case "$body" in
            "${SIG[$s]}"*) run "gh api -X DELETE \"repos/$REPO/issues/comments/$cid\" >/dev/null" && pruned=$((pruned+1)); break ;;
        esac
    done
done < <(gh api "repos/$REPO/issues/$ISSUE/comments" --paginate --jq '.[] | [.id, (.body|split("\n")[0])] | @tsv' 2>/dev/null)
echo "  ✓ deleted $pruned superseded comment(s): $prune_stages"

echo ""
if [ "$DRYRUN" -eq 1 ]; then
    echo "Dry run — nothing changed."
else
    echo "Done. Edit the issue body if you haven't, then the dispatcher regenerates"
    echo "'$STAGE' → … → sf:plan-review on its next tick (<=5 min)."
fi
